### ISSUE TITLE
'Refusing to install picture-tube as a dependency of itself' when installing with npm

### ISSUE THREAD

**Issue by Portalboy** [substack/picture-tube#9]
This is on Ubuntu 16.04.02.

First I clone the repo:
`$ git clone https://github.com/substack/picture-tube`

Then enter the project:
`$ cd picture-tube`

When I run:
`$ sudo npm install picture-tube`

I get:
```npm ERR! Linux 4.8.0-56-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "picture-tube"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ENOSELF

npm ERR! Refusing to install picture-tube as a dependency of itself
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/<user>/git_projects/picture-tube/npm-debug.log
<user>@<host>:~/git_projects/picture-tube$
```

Afterwards, trying to run gives me this:
```
$ picture-tube
/usr/bin/env: ‘node’: No such file or directory
```

Here is the log file mentioned in the error:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'install', 'picture-tube' ]
2 info using npm@3.5.2
3 info using node@v4.2.6
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData picture-tube
8 silly fetchNamedPackageData picture-tube
9 silly mapToRegistry name picture-tube
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry uri https://registry.npmjs.org/picture-tube
13 verbose request uri https://registry.npmjs.org/picture-tube
14 verbose request no auth needed
15 info attempt registry request try #1 at 1:42:08 PM
16 verbose request id 0fa1b0774c73e503
17 verbose etag W/"559710f7-22a9"
18 verbose lastModified Fri, 03 Jul 2015 22:47:19 GMT
19 http request GET https://registry.npmjs.org/picture-tube
20 http 304 https://registry.npmjs.org/picture-tube
21 verbose headers { date: 'Thu, 06 Jul 2017 18:42:08 GMT',
21 verbose headers   via: '1.1 varnish',
21 verbose headers   'cache-control': 'max-age=300',
21 verbose headers   etag: 'W/"559710f7-22a9"',
21 verbose headers   age: '0',
21 verbose headers   connection: 'keep-alive',
21 verbose headers   'x-served-by': 'cache-dfw1846-DFW',
21 verbose headers   'x-cache': 'HIT',
21 verbose headers   'x-cache-hits': '1',
21 verbose headers   'x-timer': 'S1499366528.365661,VS0,VE48',
21 verbose headers   vary: 'Accept-Encoding' }
22 silly get cb [ 304,
22 silly get   { date: 'Thu, 06 Jul 2017 18:42:08 GMT',
22 silly get     via: '1.1 varnish',
22 silly get     'cache-control': 'max-age=300',
22 silly get     etag: 'W/"559710f7-22a9"',
22 silly get     age: '0',
22 silly get     connection: 'keep-alive',
22 silly get     'x-served-by': 'cache-dfw1846-DFW',
22 silly get     'x-cache': 'HIT',
22 silly get     'x-cache-hits': '1',
22 silly get     'x-timer': 'S1499366528.365661,VS0,VE48',
22 silly get     vary: 'Accept-Encoding' } ]
23 verbose etag https://registry.npmjs.org/picture-tube from cache
24 verbose get saving picture-tube to /home/joshua/.npm/registry.npmjs.org/picture-tube/.cache.json
25 silly install normalizeTree
26 silly loadCurrentTree Finishing
27 silly loadIdealTree Starting
28 silly install loadIdealTree
29 silly cloneCurrentTree Starting
30 silly install cloneCurrentTreeToIdealTree
31 silly cloneCurrentTree Finishing
32 silly loadShrinkwrap Starting
33 silly install loadShrinkwrap
34 silly loadShrinkwrap Finishing
35 silly loadAllDepsIntoIdealTree Starting
36 silly install loadAllDepsIntoIdealTree
37 silly rollbackFailedOptional Starting
38 silly rollbackFailedOptional Finishing
39 silly runTopLevelLifecycles Starting
40 silly runTopLevelLifecycles Finishing
41 silly install printInstalled
42 verbose stack Error: Refusing to install picture-tube as a dependency of itself
42 verbose stack     at checkSelf (/usr/share/npm/lib/install/validate-args.js:40:14)
42 verbose stack     at Array.<anonymous> (/usr/share/npm/node_modules/slide/lib/bind-actor.js:15:8)
42 verbose stack     at LOOP (/usr/share/npm/node_modules/slide/lib/chain.js:15:14)
42 verbose stack     at chain (/usr/share/npm/node_modules/slide/lib/chain.js:20:5)
42 verbose stack     at /usr/share/npm/lib/install/validate-args.js:15:5
42 verbose stack     at /usr/share/npm/node_modules/slide/lib/async-map.js:52:35
42 verbose stack     at Array.forEach (native)
42 verbose stack     at /usr/share/npm/node_modules/slide/lib/async-map.js:52:11
42 verbose stack     at Array.forEach (native)
42 verbose stack     at asyncMap (/usr/share/npm/node_modules/slide/lib/async-map.js:51:8)
43 verbose cwd /home/joshua/git_projects/picture-tube
44 error Linux 4.8.0-56-generic
45 error argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "picture-tube"
46 error node v4.2.6
47 error npm  v3.5.2
48 error code ENOSELF
49 error Refusing to install picture-tube as a dependency of itself
50 error If you need help, you may report this error at:
50 error     <https://github.com/npm/npm/issues>
51 verbose exit [ 1, true ]
```

**Comment by Portalboy** [comment]
Upon doing more research it appears this was caused by my lack of knowledge on what npm is actually doing.
I'll start a new issue for my `/usr/bin/env: ‘node’: No such file or directory` problem which is separate.
